name: TestPlugin
version: 1.0
author: Desolstice
main: me.desolstice.TestPlugin.TestPlugin
api-version: 1.16

commands:
  teleport:
    description: Teleports the player to another player
    usage: /teleport <targetPlayer>
    permission: TestPlugin.Teleport